Upgrade tools
gaearon/react-proxy pull request #77
Opened 2017-05-15 21:39 UTC by agoldis

@wkwiatek as we've discussed at #40 
- Upgrade tooling to modern versions
- Use `enzyme` as tests shallow renderer
- Modify some tests for usage with `enzyme`

🎶  I still have to move more test and use new enzyme-based renderer. I have only resolved the tests of `tests/consistency` (I will open a distinct PR with `createProxy` changes). Other tests are just modified to prevent exceptions, but they are not passing

2017-05-16 10:52 UTC, wkwiatek requested changes
Thanks you for the PR! I'll try to check it this week by running the code when it's merged.

2017-05-16 10:52 UTC, wkwiatek commented on test/inheritance.js
> +      let instance = renderer.render(<DerivedProxy />);
Are you using this one somewhere else (`let`)? I can't see.

2017-05-16 10:52 UTC, wkwiatek commented on test/helpers/createShallowRenderer.js
> +let factory = function (old) {
Isn't `const` a better options here?

2017-05-16 10:52 UTC, wkwiatek commented on test/helpers/_createShallowRenderer.js
> +  This is taken from React's TestUtils,
OK. I believe it works then ;)

2017-05-16 10:52 UTC, wkwiatek commented on test/consistency.js
> +    xit('[why is the test important?] preserves toString() of methods', () => {
I guess there was a case when the original methods had `toString()` while the proxied one hadn't.

2017-05-16 10:52 UTC, wkwiatek commented on test/consistency.js
> +    xit('[do not get it] should not crash if new Function() throws', () => {
Can't help here, but I think it may not be relevant in the new approach either.

2017-05-16 10:52 UTC, wkwiatek commented on test/consistency.js
> +      expect(Proxy.displayName).tfoEqual('Foo (Custom)');
typo: `tfoEqual`

2017-05-16 20:26 UTC, agoldis commented
@wkwiatek thanks for the comments!
I want to go forward and modify other test files to use enzyme (just to make them work)
After the tools are upgraded I could start to fix the tests slowly

I can't figure out how to create convenient and not huge PRs, as i am going to change another 10 test files, do you have any ideas?

2017-05-17 09:25 UTC, wkwiatek commented
For me you can create even bigger PRs, but also you can still push a bunch of changes as you're progressing. 

Once again, thanks for your help!

2017-05-17 09:25 UTC, merged